"""Added property table1

Revision ID: 066e4090915b
Revises: 319577964900
Create Date: 2022-09-08 12:38:37.110825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066e4090915b'
down_revision = '319577964900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propdetails', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('propdetails', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propdetails', 'created_at')
    op.drop_column('propdetails', 'updated_at')
    # ### end Alembic commands ###
