"""Added property table2

Revision ID: 7c22e70f279d
Revises: e7a6aa8f9b15
Create Date: 2022-09-21 11:57:08.070916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c22e70f279d'
down_revision = 'e7a6aa8f9b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propdetails', sa.Column('architects', sa.String(), nullable=True))
    op.add_column('propdetails', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('propdetails', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('propdetails', sa.Column('manufacturers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propdetails', 'manufacturers')
    op.drop_column('propdetails', 'year')
    op.drop_column('propdetails', 'area')
    op.drop_column('propdetails', 'architects')
    # ### end Alembic commands ###
