"""Added property table2

Revision ID: e7a6aa8f9b15
Revises: a3dd2cc7fd3b
Create Date: 2022-09-09 15:18:11.134107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a6aa8f9b15'
down_revision = 'a3dd2cc7fd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
